#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 
#bspc monitor HDMI-2 -d 5 6 7 8

# xrandr --output HDMI-1 --primary --mode 1920x1080 --rotate normal --output HDMI-2 --mode 1920#x1080 --rotate normal --right-of HDMI-1



bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)




bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
